# Generated by Django 3.0.6 on 2020-05-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d'),
        ),
    ]
